### ISSUE TITLE
[QUESTION] Vue Compatibility

### ISSUE THREAD

**Issue by go4cas** [hyoban/unocss-preset-shadcn#1]
Cool preset! I tried to use this with a Vue 3 (Vite) app, but could not get it to work. When adding components, these are added as `.tsx`. Is there a guide to get this working with Vue components?

**Comment by hyoban** [comment]
Are you using it with https://www.shadcn-vue.com ?

I haven't tried it yet, I will try it and create a demo.

**Comment by hyoban** [comment]
Hi, I created a [demo](https://github.com/hyoban/unocss-preset-shadcn/tree/main/examples/shadcn-vue) for shadcn-vue.

The key issue is that you need to add the following configuration to `uno.config.ts`, you can find updated setup steps in the readme.

```ts
content: {
  pipeline: {
    include: [
      /\.(vue|svelte|[jt]s|[jt]sx|mdx?|astro|elm|php|phtml|html)($|\?)/,
    ],
  },
},
```

**Comment by go4cas** [comment]
Thanks, @hyoban!

I have started over, using the updated `README` guide. Everything working well now, thanks!

The only addition I had to make was, adding the following to `vite.config.js`:

```javascript
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
```
