### ISSUE TITLE
Classes not working on dev server

### ISSUE THREAD

**Issue by brokuka** [hyoban/unocss-preset-shadcn#8]
### Describe the bug

After I started the local server I encountered that the styles do not work.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-475whq?file=components.json,app.vue,package.json,nuxt.config.ts

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 4.70 GB / 15.92 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.3 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.81)
    Internet Explorer: 11.0.19041.4355
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/hyoban/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/hyoban/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hyoban** [comment]
There is no src folder in your project, you need to change to `'components/**/*.{js,ts}'`

https://stackblitz.com/edit/nuxt-starter-43myh5?file=components.json,app.vue,package.json,uno.config.ts

**Comment by brokuka** [comment]
> There is no src folder in your project, you need to change to `'components/**/*.{js,ts}'`
> 
> https://stackblitz.com/edit/nuxt-starter-43myh5?file=components.json,app.vue,package.json,uno.config.ts

Good catch!
